"""
Utilities for reading and patching GROMACS .mdp files.
Preserves comments and formatting where possible.
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path
from datetime import datetime, timezone

from agent.recovery.models import MDPPatch


def read_mdp(mdp_path: str | Path) -> dict[str, str]:
    """
    Parse an .mdp file into a dict of {parameter: value}.
    Strips inline comments. Ignores comment-only lines.

    Returns:
        Dict mapping parameter names to their string values.
    """
    params: dict[str, str] = {}
    path = Path(mdp_path)

    for line in path.read_text().splitlines():
        # Strip inline comments
        line = re.sub(r";.*$", "", line).strip()
        if not line or "=" not in line:
            continue
        key, _, value = line.partition("=")
        params[key.strip().lower()] = value.strip()

    return params


def write_mdp(params: dict[str, str], mdp_path: str | Path) -> None:
    """
    Write a parameter dict back to an .mdp file.
    One parameter per line, aligned for readability.
    """
    path = Path(mdp_path)
    lines = [
        f"; Auto-generated by GROMACS agent — "
        f"{datetime.now(timezone.utc).isoformat()}\n"
    ]
    for key, value in params.items():
        lines.append(f"{key:<32} = {value}\n")
    path.write_text("".join(lines))


def apply_patches(
    mdp_path: str | Path,
    patches: list[MDPPatch],
    backup: bool = True,
) -> dict[str, tuple[str, str]]:
    """
    Apply a list of MDPPatch objects to an .mdp file in-place.

    Args:
        mdp_path: Path to the .mdp file to patch.
        patches:  List of MDPPatch objects from RecoveryPlanner.
        backup:   If True, save a .bak copy before patching.

    Returns:
        Dict of {parameter: (old_value, new_value)} for all applied patches.
    """
    path = Path(mdp_path)

    if backup:
        backup_path = path.with_suffix(
            f".bak_{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%S')}"
        )
        shutil.copy2(path, backup_path)

    params = read_mdp(path)
    applied: dict[str, tuple[str, str]] = {}

    for patch in patches:
        key = patch.parameter.lower()
        old_val = params.get(key, "<not set>")
        params[key] = patch.new_value
        applied[key] = (old_val, patch.new_value)

    write_mdp(params, path)
    return applied


def copy_template(
    template_name: str,
    dest_path: str | Path,
    templates_dir: str | Path = "mdp_templates",
) -> Path:
    """
    Copy an MDP template to the working directory.

    Args:
        template_name: Filename, e.g. 'em.mdp', 'nvt.mdp'.
        dest_path:     Destination path for the copy.
        templates_dir: Directory containing MDP templates.

    Returns:
        Path to the copied file.
    """
    src = Path(templates_dir) / template_name
    dst = Path(dest_path)
    if not src.exists():
        raise FileNotFoundError(
            f"MDP template not found: {src}. "
            f"Available templates: {list(Path(templates_dir).glob('*.mdp'))}"
        )
    shutil.copy2(src, dst)
    return dst