"""
Utilities for reading and patching GROMACS .mdp files.
Preserves comments and formatting where possible.
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path
from datetime import datetime, timezone

from agent.recovery.models import MDPPatch


def read_mdp(mdp_path: str | Path) -> dict[str, str]:
    """
    Parse an .mdp file into a dict of {parameter: value}.
    Strips inline comments. Ignores comment-only lines.
    """
    params: dict[str, str] = {}
    path = Path(mdp_path)

    if not path.exists():
        raise FileNotFoundError(f"MDP file not found: {path}")

    for line in path.read_text().splitlines():
        line = re.sub(r";.*$", "", line).strip()
        if not line or "=" not in line:
            continue
        key, _, value = line.partition("=")
        params[key.strip().lower()] = value.strip()

    return params


def write_mdp(params: dict[str, str], mdp_path: str | Path) -> None:
    """
    Write a parameter dict back to an .mdp file.
    Creates parent directories if they do not exist.  # ← fix
    """
    path = Path(mdp_path)
    path.parent.mkdir(parents=True, exist_ok=True)   # ← fix

    lines = [
        f"; Auto-generated by GROMACS agent — "
        f"{datetime.now(timezone.utc).isoformat()}\n"
    ]
    for key, value in params.items():
        lines.append(f"{key:<32} = {value}\n")
    path.write_text("".join(lines))


def apply_patches(
    mdp_path: str | Path,
    patches: list[MDPPatch],
    backup: bool = True,
) -> dict[str, tuple[str, str]]:
    """
    Apply a list of MDPPatch objects to an .mdp file in-place.
    """
    path = Path(mdp_path)

    if backup:
        backup_path = path.with_suffix(
            f".bak_{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%S')}"
        )
        shutil.copy2(path, backup_path)

    params = read_mdp(path)
    applied: dict[str, tuple[str, str]] = {}

    for patch in patches:
        key = patch.parameter.lower()
        old_val = params.get(key, "<not set>")
        params[key] = patch.new_value
        applied[key] = (old_val, patch.new_value)

    write_mdp(params, path)   # write_mdp now handles mkdir
    return applied


def copy_template(
    template_name: str,
    dest_path: str | Path,
    templates_dir: str | Path = "mdp_templates",
) -> Path:
    """
    Copy an MDP template to the working directory.
    Creates destination parent directories if they do not exist.  # ← fix
    """
    src = Path(templates_dir) / template_name
    dst = Path(dest_path)

    if not src.exists():
        raise FileNotFoundError(
            f"MDP template not found: {src}. "
            f"Available templates: {list(Path(templates_dir).glob('*.mdp'))}"
        )

    dst.parent.mkdir(parents=True, exist_ok=True)   # ← fix
    shutil.copy2(src, dst)
    return dst